### ISSUE TITLE
[mg24x] LHE generation fails with current master branch 

### ISSUE THREAD

**Issue by gkrintir** [cms-sw/genproductions#1699] opened 2018-03-02 18:29 UTC
Hello, 

I am having an issue--that I cannot figure out--to generate lhe files on lxplus batch using the current master branch and for the thq input card:

https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Higgs/thq_4f_ckm_LO_ctcvcp_MH (randomly chosen the 126 mass point)

Checking out an older version of the master branch (for which I remembered the generation was working properly):

git checkout `git rev-list -n 1 --before="2017-11-29 11:09" master`

I could indeed produce lhe files successfully.

The output along with log and tar balls can be found in:

/afs/cern.ch/work/g/gkrintir/public/forGEN/current_master/

and

/afs/cern.ch/work/g/gkrintir/public/forGEN/29thofNov2017_master/

respectively. Any help appreciated.

Regards

**Comment by AndreasAlbert** [comment] 2018-03-05 09:18
Hi,

the issue seems to be in [L246 of runcmsgrid.sh](https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L240), which throws this error:

`mv: cannot move 'cmsgrid_final.lhe' to 'process/madevent/Events/GridRun_1/unweighted_events.lhe': No such file or directory`

The problem is that `GridRun_1` does not exist, only `GridRun_10` does, because the users initial choice for the seed (in my case 1) is multiplied by ten in [L79](https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L79).

@perrozzi may want to comment

**Comment by gkrintir** [comment] 2018-03-05 09:32
Thanks a lot @AndreasAlbert 

If that helps, the relevant changes have been introduced in the commit:
https://github.com/cms-sw/genproductions/commit/4fc088bf16a6b40c036d18e9d39cced3449aeeb9#diff-29877b5e69e81b130f1a5c979e368a18

and further edited in:
https://github.com/cms-sw/genproductions/commit/e9807a9d2dd19ca814616f6b0581acc0937706d1#diff-29877b5e69e81b130f1a5c979e368a18


Regards

**Comment by gkrintir** [comment] 2018-03-09 14:14
Hi @perrozzi any recommendation ?

Thanks a lot in advance

**Comment by kdlong** [comment] 2018-03-13 14:12
Should be able to change $rnum to $run_random_start in these few lines

https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L240-L244

**Comment by gkrintir** [comment] 2018-03-13 14:42
Thanks a lot @kdlong 

Fix in https://github.com/cms-sw/genproductions/pull/1716

Regards

**Comment by perrozzi** [comment] 2018-03-13 15:13
@gkrintir have you tested it?

**Comment by gkrintir** [comment] 2018-03-13 15:16
Hi @perrozzi  yes with this substitution it works ;D

**Comment by kdlong** [comment] 2018-03-13 15:17
Thanks a lot @gkrintir

**Comment by perrozzi** [comment] 2018-03-13 16:07
thanks, PR merger, closing the issue then

**Closed by perrozzi** 2018-03-13 16:07 UTC
