### ISSUE TITLE
[MG / CMSConnect] Propagation of errors still not always working

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1553] opened 2017-11-23 17:40 UTC
Even after including the changes in #1541, I encounter cases where I get 

>    Error when reading <open file '/local-scratch/aalbert/genproductions/bin/MadGraph5_aMCatNLO/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-1000_mh4-200/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-1000_mh4-200_gridpack/work/processtmp/SubProcesses/P0_gg_xdxdxll/G1.26_12/results.dat', mode 'r' at 0x27cf660>

because the sub-job encounters this error:

> ../madevent: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory

@khurtado  Should this still happen?

**Comment by khurtado** [comment] 2017-11-23 17:58
@AndreasAlbert : This can still happen if there are worker nodes with cvmfs issues, but madgraph should be able to resubmit the job now.

Your job in particular reported exit code 127 and ran at Wisconsin:

$ condor_history 1055955 -af:h ExitCode MachineAttrGLIDEIN_CMSSite0
ExitCode MachineAttrGLIDEIN_CMSSite0
127      T2_US_Wisconsin

Meaning the patch did work, so I'm not sure why the madgraph cluster manager is not doing a resubmission.
I have blacklisted T2_US_Wisconsin temporarily in the default list (so, the list used whenever `source /etc/ciconnect/set_condor_sites.sh <pattern>` is not explicitely used).

I will need to investigate further this one next week.

**Comment by kdlong** [comment] 2017-11-24 08:11
@khurtado: by cvmfs issues, do you mean that the jobs don't have cvmfs mounted or that its available but not a proper version/installation?

When I submit jobs directly to Wisconsin, we use the requirement ```TARGET.UWCMS_CVMFS_Exists```. Is there any global condition like this that can be applied to all CMS sites? Doesn't something similar have to be used for the production jobs?

**Comment by khurtado** [comment] 2017-11-24 15:53
@kdlong : I mean that `/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/gcc/4.8.1/lib64/` was not readable for some reason. This can happen for several reasons, for example:

- The CVMFS mount crashed and the production gWMS frontend hasn't updated the CVMFS flag yet (there are validation scripts that run every X minutes to detect worker nodes with cvmfs issues, but these run periodically and I don't know what the time period is for WISC for example).
- SQUID issues. CVMFS is available but it can timeout requests due to high load on the cache proxy in the site. This will be transient.
- Environment issues: Singularity doesn't set `LD_LIBRARY_PATH` properly, so even if the libraries are available, the job can't find it in the environment. This should be fixed with the patches we apply for the madgraph templates though.

I just tried to reproduce the issue but was unable to. So, I have made a PR in #1557. @AndreasAlbert  could you add that to your future workflows? If you happen to see this error, at least we will be able to see what the job was seeing and discard (or identify) environment issues.

**Comment by khurtado** [comment] 2017-11-24 19:23
@AndreasAlbert @kdlong : I updated #1557 with something that should hopefully make resubmission happen when cases like these occur.

JFYI, from the tests I did with bare condor on WISC, out of 1000 test jobs submitted, 5 of them landed in `e487.chtc.wisc.edu` always failing, while other worker nodes would find `libgfortran` in the environment just fine.

**Comment by khurtado** [comment] 2017-12-07 15:25
Since #1557 has been merged and @AndreasAlbert was able to finish 15 gridpacks without this issues after applying such PR, I propose we close this issue.

**Closed** 2017-12-08 07:13 UTC
Labels: Bug: CMS scripts -- MG, enhancement
