### ISSUE TITLE
CMSConnect in MadGraph v2.5.5

### ISSUE THREAD

**Issue by kdlong** [cms-sw/genproductions#1252] opened 2017-07-25 13:25 UTC
Port changes in master branch allowing gridpack generation with CMSConnect to 2.5 branch.

@khurtado, any projections on this? I think it would be very useful to have for testing the Z/Wgamma samples which are very resource intensive.

**Comment by khurtado** [comment] 2017-07-25 14:02
I have this on my todo list, but haven't been able to work on it yet, hope to have it for the middle of next week though.

**Comment by khurtado** [comment] 2017-07-27 18:48
@kdlong Just made a pull request for this:  #1261

**Comment by kdlong** [comment] 2017-07-27 19:42
Great, thanks! Testing at T2_US_Wisconsin now.

**Comment by khurtado** [comment] 2017-07-28 14:45
Thanks! Let me know how that goes.

**Comment by kdlong** [comment] 2017-07-30 20:57
It worked without any problems. We just updated to 8.6, so that also doesn't seem to be a problem. Maybe we could add the line 

PYTHONPATH=/usr/lib64/python2.6/site-packages:$PYTHONPATH

into the submit_condor_gridpack_generation.sh script since this seems to be the expected location, and if the packages are located elsewhere this line shouldn't cause any harm. What do you think?

**Comment by bendavid** [comment] 2017-07-30 22:05
This could break things if there are a mix of python versions.  Better to add only the path for the needed condor bindings package.

**Comment by khurtado** [comment] 2017-07-31 15:14
@kdlong: I would prefer not to hardcode that directory in the PYTHONPATH every time if possible. 
If any change is necessary, it should be added into the `source_condor.sh` script which `source_condor / source_cmsconnect` depend on. This script currently finds the PATH for the python bindings in the local system as long as it is available in the and python 2.x is the default version in the system, which is the usual in EL6/7 based systems and will probably be the case until 2020 (end of support of python 2.7.x). If this becomes a problem we should push to have these dependencies included in CVMFS ( #1212 ) . We could also easily include these 2 libraries in the github repository, but then somebody would need to keep track of updates when needed, so I would rather not go that route.

 @bendavid The problem is the condor bindings only have its own directory when they are installed from the condor tarball binaries. When condor and the bindings are  installed from RPMS, `htcondor.so` and `classads.so` are installed in the parent directory on EL6/7-based systems, so the whole `site-packages` will be included in most cases.
In any case, since we setup the CMS framework before doing any actual work in madgraph and CVMFS PATHs are prepended in the PYTHONPATH, a module will only tried to be used from the local system if it's not avaialble in cvmfs... and at this point the only candidate for that would be the condor python bindings.

**Closed** 2017-08-01 21:06 UTC
