### ISSUE TITLE
[powheg]LHAPDF::RangeError

### ISSUE THREAD

**Issue by gkrintir** [cms-sw/genproductions#1506] opened 2017-11-10 11:45 UTC
Concerning the diboson (ZZ,WZ) production (ZZTo2L2Nu/ZZTo4L,WZTo3LNu) with powheg, has anyone already tried the gridpack creation with the NNPDF31 set ?

When I tested the 5 TeV cards [1] with the 260000 --> 306000 substitution I am getting the exception in step 2:

"
terminate called after throwing an instance of 'LHAPDF::RangeError'
  what():  Unphysical Q2 given: -nan
"

Can someone reproduce the error ? Can this be somehow related to mllmin cut ?

Strangely (?) for WW it works.

Regards and thanks

[1] https://github.com/cms-sw/genproductions/tree/powheg_gcc48x/bin/Powheg/production/5TeV

**Comment by perrozzi** [comment] 2017-11-13 08:38
Have you upgraded your genproductions repository to cms-sw:genproductions/master ?

**Comment by gkrintir** [comment] 2017-11-13 10:48
Hi Luca, sorry for not being specific with that. 
Yes, that was using the master branch. I referred to gcc48x only as an example to the card I used, with the only difference of 260000 --> 306000 substitution for PDF.

**Comment by perrozzi** [comment] 2017-11-13 11:25
can you please point to the exact datacard and a log of the compilation?

**Comment by gkrintir** [comment] 2017-11-13 13:35
Sure. I have just checked out the master again and rerun e.g. for WZ the input cards and log files can be found in:

/afs/cern.ch/user/g/gkrintir/public/ForLuca/WZTo3lNu_NNPDF31_5TeV

I have two instances; the first is with no PDF reweighing ('WZ_lllnu_NNPDF31_NoReweight_5TeV') and the second with PDF reweighing 

In either case, the error is the same.

PS: For WW/ZZ the processes are still running.

**Comment by gkrintir** [comment] 2017-11-13 14:16
[Update]

Now also WW finished. Input card and log in:

/afs/cern.ch/user/g/gkrintir/public/ForLuca/WWTo2L2Nu_NNPDF31_5TeV

As I initially said, WW seems indeed to work fine.

PS: For ZZ the process is still running.

**Comment by gkrintir** [comment] 2017-11-20 22:44
Thanks a lot Kenneth.

I guess the same should happen also for ZZ ? I got the same exception, though not for WW.

**Comment by agrohsje** [comment] 2017-11-21 08:09
That could be as it is caused by a massless particle that is given to a routine assuming massive ones. The authors didn't reply yet. Anyway. I will point out the issue in ZZ as soon as we get feedback.

**Comment by agrohsje** [comment] 2018-01-16 10:03
We should close this thread. The authors provided an (unsatisfying) solution by adding the attached pdf [1] file to the wz and zz directory. It doesn't solve the seg fault but avoids it. 
[1] www.desy.de/~agrohsje/hidden/lhapdf6if.f

**Closed** 2018-01-16 13:02 UTC
Labels: Bug: Powheg
